"""empty message

Revision ID: 0a900baefa63
Revises: 
Create Date: 2020-04-06 19:40:48.960656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a900baefa63'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('age_group', sa.String(length=10), nullable=True),
    sa.Column('country_of_birth', sa.String(length=100), nullable=True),
    sa.Column('education_level', sa.String(length=100), nullable=True),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.Column('latest_country', sa.String(length=100), nullable=True),
    sa.Column('income', sa.String(length=100), nullable=True),
    sa.Column('completed_form', sa.Boolean(), nullable=True),
    sa.Column('completed_study', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('card_set',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('measure', sa.String(length=100), nullable=True),
    sa.Column('Admin', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Admin'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('Admin', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Admin'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('image', sa.String(length=100), nullable=True),
    sa.Column('Admin', sa.Integer(), nullable=True),
    sa.Column('card_set_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Admin'], ['user.id'], ),
    sa.ForeignKeyConstraint(['card_set_id'], ['card_set.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('study',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('image', sa.String(length=100), nullable=True),
    sa.Column('data_values', sa.Integer(), nullable=True),
    sa.Column('number_of_columns', sa.Integer(), nullable=True),
    sa.Column('number_of_rows', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('mail_sent', sa.Boolean(), nullable=True),
    sa.Column('card_set_x_id', sa.Integer(), nullable=True),
    sa.Column('card_set_y_id', sa.Integer(), nullable=True),
    sa.Column('Admin', sa.Integer(), nullable=True),
    sa.Column('user_group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Admin'], ['user.id'], ),
    sa.ForeignKeyConstraint(['card_set_x_id'], ['card_set.id'], ),
    sa.ForeignKeyConstraint(['card_set_y_id'], ['card_set.id'], ),
    sa.ForeignKeyConstraint(['user_group_id'], ['user_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_value_label',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=500), nullable=True),
    sa.Column('Study', sa.Integer(), nullable=True),
    sa.Column('Admin', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Admin'], ['user.id'], ),
    sa.ForeignKeyConstraint(['Study'], ['study.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cards_x', sa.JSON(), nullable=True),
    sa.Column('cards_y', sa.JSON(), nullable=True),
    sa.Column('data_values', sa.JSON(), nullable=True),
    sa.Column('Admin', sa.Integer(), nullable=True),
    sa.Column('Participant', sa.Integer(), nullable=True),
    sa.Column('study_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Admin'], ['user.id'], ),
    sa.ForeignKeyConstraint(['Participant'], ['user.id'], ),
    sa.ForeignKeyConstraint(['study_id'], ['study.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('heat_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('values', sa.JSON(), nullable=True),
    sa.Column('is_count', sa.Boolean(), nullable=True),
    sa.Column('card_x_id', sa.Integer(), nullable=True),
    sa.Column('card_y_id', sa.Integer(), nullable=True),
    sa.Column('Admin', sa.Integer(), nullable=True),
    sa.Column('data_value_label', sa.Integer(), nullable=True),
    sa.Column('study_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Admin'], ['user.id'], ),
    sa.ForeignKeyConstraint(['card_x_id'], ['card.id'], ),
    sa.ForeignKeyConstraint(['card_y_id'], ['card.id'], ),
    sa.ForeignKeyConstraint(['data_value_label'], ['data_value_label.id'], ),
    sa.ForeignKeyConstraint(['study_id'], ['study.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('heat_map')
    op.drop_table('response')
    op.drop_table('data_value_label')
    op.drop_table('study')
    op.drop_table('card')
    op.drop_table('user_group')
    op.drop_table('card_set')
    op.drop_table('user')
    # ### end Alembic commands ###
