"""empty message

Revision ID: 5e05ae8b8ce8
Revises: f1179f3d9134
Create Date: 2020-04-08 16:36:08.875835

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5e05ae8b8ce8'
down_revision = 'f1179f3d9134'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('heat_map', sa.Column('data_value_label_id', sa.Integer(), nullable=True))
    op.drop_constraint('heat_map_ibfk_4', 'heat_map', type_='foreignkey')
    op.create_foreign_key(None, 'heat_map', 'data_value_label', ['data_value_label_id'], ['id'])
    op.drop_column('heat_map', 'data_value_label')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('heat_map', sa.Column('data_value_label', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'heat_map', type_='foreignkey')
    op.create_foreign_key('heat_map_ibfk_4', 'heat_map', 'data_value_label', ['data_value_label'], ['id'])
    op.drop_column('heat_map', 'data_value_label_id')
    # ### end Alembic commands ###
