"""empty message

Revision ID: f1179f3d9134
Revises: 0a900baefa63
Create Date: 2020-04-06 19:41:59.979593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1179f3d9134'
down_revision = '0a900baefa63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('UserGroup', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'user_group', ['UserGroup'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'UserGroup')
    # ### end Alembic commands ###
